/*
 * ASI (Mach Airspeed Indicator) Host -- Gulfstream-style
 * Procedural rendering -- no bitmap assets
 * Non-linear airspeed dial, barber-pole VMO pointer,
 * Mach drum display, OFF/VMO flag
 *
 * Usage: asi_host.exe [pi_ip]
 *
 * Controls:
 *   Up/Down      -- IAS
 *   Left/Right   -- VMO pointer
 *   Q/W          -- Mach (manual adjust)
 *   SPACE        -- toggle auto animation
 *   R            -- reset
 *   ESC          -- quit
 *
 * ===================================================================
 * OVERVIEW
 * ===================================================================
 *
 * This program implements a complete Gulfstream-style Mach Airspeed
 * Indicator (ASI) rendered entirely in software -- no bitmap sprites,
 * no texture atlas, no image files of any kind. Every pixel on the
 * instrument face is computed procedurally: the dial markings, the
 * numbers (drawn from a built-in 5x7 bitmap font), the IAS pointer,
 * the barber-pole VMO pointer, the Mach drum window, and the warning
 * flags are all generated by arithmetic alone.
 *
 * The instrument faithfully reproduces the non-linear scale of a real
 * Gulfstream ASI. On the actual aircraft's airspeed indicator, the
 * low-speed range (60-200 kts) is spread across roughly 180 degrees
 * of arc, giving the pilot fine resolution where it matters most
 * (approach and departure speeds). The high-speed range (200-500 kts)
 * is compressed into the remaining arc -- typical of all mechanical
 * airspeed indicators, which use a shaped cam to convert linear
 * Pitot-static pressure into non-linear dial rotation.
 *
 * The host runs on a Windows PC and transmits instrument state over
 * UDP to a Raspberry Pi, which drives the actual physical display
 * hardware. The UDP packet is a simple 16-byte struct sent at ~30 Hz.
 *
 * RENDERING STRATEGY:
 *   - The static dial face (bezel, tick marks, numbers, labels) is
 *     rendered ONCE at startup into a pre-rendered background buffer.
 *   - Each frame, the background is memcpy'd into the active
 *     framebuffer, then the dynamic elements (pointers, Mach drum,
 *     flags, hub) are drawn on top. This avoids re-computing
 *     hundreds of trig calls and font lookups every frame.
 *
 * BUILD:
 *   gcc -O2 -o asi_host.exe asi_host.c -lSDL2 -lws2_32 -lm
 */
#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include <winsock2.h>

#pragma comment(lib, "ws2_32.lib")

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ================================================================== */
/*  UDP packet definition                                             */
/* ================================================================== */
/*
 * The AsiPacket structure is the wire format sent to the Raspberry Pi
 * receiver at ~30 Hz. It uses a simple flat struct layout with no
 * padding concerns (all fields are naturally aligned).
 *
 * Fields:
 *   instrument_id  -- Identifies which instrument this packet is for.
 *                     The Pi receiver demuxes packets by this field,
 *                     allowing multiple instruments to share one UDP
 *                     port. Value 5 = ASI.
 *   ias            -- Indicated Airspeed in knots (60-500 range).
 *   mach           -- Mach number displayed in the drum window
 *                     (0.10-0.99). On a real aircraft, this comes from
 *                     the Air Data Computer (ADC), not the ASI itself,
 *                     but we bundle it here for simplicity.
 *   vmo            -- Maximum Operating Velocity in knots. The barber-
 *                     pole pointer is driven to this value. On the
 *                     real aircraft, VMO varies with altitude (lower
 *                     at high altitude) and is computed by the ADC.
 *
 * Byte layout (little-endian, x86):
 *   Offset  Size  Field
 *   0       4     instrument_id  (uint32_t, value = 5)
 *   4       4     ias            (IEEE 754 float, knots)
 *   8       4     mach           (IEEE 754 float, 0.10-0.99)
 *   12      4     vmo            (IEEE 754 float, knots)
 *   Total: 16 bytes per packet
 */
typedef struct {
    uint32_t instrument_id;     /* 5 = ASI */
    float    ias;               /* knots */
    float    mach;              /* 0.10-0.99 */
    float    vmo;               /* knots */
} AsiPacket;
#define INSTRUMENT_ASI  5
#define PI_PORT         5555        /* UDP destination port on the Pi */
#define SEND_INTERVAL   33          /* ~30 Hz transmit rate (ms) */

/* ================================================================== */
/*  Display geometry constants                                        */
/* ================================================================== */
/*
 * The window is divided into two regions:
 *
 *   1. The instrument face (DISP_W x DISP_H = 480x480 pixels).
 *      This is a square area containing the round ASI dial.
 *      The center of the dial is at (CX, CY) = (240, 240).
 *
 *   2. The control panel (WIN_W x PANEL_H = 480x110 pixels),
 *      appended below the instrument. This contains three groups
 *      of controls (IAS, MACH, VMO), each with a label, a
 *      numeric readout, and left/right arrow buttons for manual
 *      adjustment.
 *
 * Total window size: 480 wide x 590 tall.
 */
#define DISP_W    480               /* instrument face width (pixels) */
#define DISP_H    480               /* instrument face height (pixels) */
#define PANEL_H   110               /* control panel height below dial */
#define WIN_W     DISP_W            /* total window width */
#define WIN_H     (DISP_H + PANEL_H) /* total window height (590) */
#define CX        240               /* dial center X */
#define CY        240               /* dial center Y */

/* ---- Panel layout (3 groups) ---- */
/*
 * The control panel is divided into 3 equal-width groups (160px each):
 *   Group 0: IAS    -- indicated airspeed control
 *   Group 1: MACH   -- Mach number control
 *   Group 2: VMO    -- VMO pointer control
 *
 * Each group has:
 *   - A gray label at the top (LABEL_Y)
 *   - A green numeric value below it (VALUE_Y)
 *   - A left arrow button and right arrow button (BTN_Y)
 *
 * The BTN_L_X / BTN_R_X macros compute button positions so they
 * sit at the left and right edges of each group with 6px padding.
 */
#define N_CONTROLS  3
#define GROUP_W     (WIN_W / N_CONTROLS)
#define BTN_W       32
#define BTN_H       28
#define BTN_Y       (DISP_H + 58)
#define LABEL_Y     (DISP_H + 14)
#define VALUE_Y     (DISP_H + 38)
#define BTN_L_X(g)  ((g) * GROUP_W + 6)
#define BTN_R_X(g)  ((g) * GROUP_W + GROUP_W - 6 - BTN_W)

/* ---- Color palette ---- */
/*
 * All colors are 32-bit ARGB (0xAARRGGBB). SDL is configured for
 * ARGB8888 pixel format. Alpha is always 0xFF (fully opaque).
 */
#define COL_PANEL_BG    0xFF1A1A1Au /* dark gray panel background */
#define COL_SEPARATOR   0xFF333333u /* thin divider lines */
#define COL_BTN_NORMAL  0xFF3A3A3Au /* button idle state */
#define COL_BTN_HOVER   0xFF505050u /* button mouse hover */
#define COL_BTN_PRESS   0xFF686868u /* button pressed */
#define COL_ARROW_C     0xFFDDDDDDu /* arrow glyph inside buttons */
#define COL_LABEL       0xFF888888u /* group label text ("IAS", etc.) */
#define COL_VALUE_G     0xFF44DD44u /* green numeric readout */

/* ================================================================== */
/*  Dial geometry constants                                           */
/* ================================================================== */
/*
 * The ASI dial is a circular instrument face with the following
 * concentric zones (from center outward):
 *
 *   HUB_R (18px)         -- center pivot hub with radial shading
 *   PTR_LEN (170px)      -- IAS and VMO pointers extend this far
 *   NUM_R (155px)         -- radial position of speed number labels
 *   TICK_INNER (171px)    -- inner edge of major tick marks
 *   TICK_MINOR_INNER      -- inner edge of minor tick marks
 *                            (DIAL_R - TICK_MIN = 183px)
 *   DIAL_R (195px)        -- outer edge of tick marks / dial ring
 *   DIAL_R+5 (200px)      -- inner edge of bezel ring
 *   DIAL_R+20 (215px)     -- outer edge of bezel ring
 *
 * Tick mark design:
 *   Major ticks are 24px long and 2px wide (TICK_MAJ = TICK_MIN*2).
 *   Minor ticks are 12px long and 1px wide.
 *   Both types share the same INNER radius (TICK_INNER) and extend
 *   outward; major ticks reach the full TICK_MAJ length while minor
 *   ticks stop at TICK_MIN. This means minor ticks appear as shorter
 *   marks starting from the same inner radius, which matches the
 *   look of a real mechanical instrument where all marks align at
 *   the inner edge.
 */
#define DIAL_R      195         /* outer edge of dial */
#define TICK_MIN    12          /* minor tick length */
#define TICK_MAJ    (TICK_MIN*2) /* major = 2x minor length */
/* Both share same inner radius; major extends outward beyond minor */
#define TICK_INNER  (DIAL_R - TICK_MAJ)  /* inner radius for major ticks */
#define TICK_MINOR_INNER (DIAL_R - TICK_MIN)  /* inner radius for minor ticks */
#define NUM_R       155         /* number center radius */
#define PTR_LEN     170         /* pointer length from center */
#define HUB_R       18          /* center hub radius */

/* ================================================================== */
/*  5x7 bitmap font                                                   */
/* ================================================================== */
/*
 * This is a minimal built-in bitmap font used for all text rendering
 * on the instrument face: speed numbers around the dial, the "IAS"
 * and "KT" labels, the Mach drum digits, the "MACH" label, and the
 * OFF/VMO flag text.
 *
 * Each glyph is 5 pixels wide and 7 pixels tall. The font data is
 * stored as an array of 7 bytes per character, where each byte
 * represents one row of the glyph. Within each byte, the most
 * significant bit used is bit 4 (0x10) for the leftmost pixel, and
 * bit 0 (0x01) for the rightmost pixel. A set bit means "draw this
 * pixel"; a clear bit means "transparent."
 *
 * Example: The digit '0' is stored as {0x0E, 0x11, 0x13, 0x15, 0x19, 0x11, 0x0E}
 *
 *   Row 0: 0x0E = 01110  →  .XXX.
 *   Row 1: 0x11 = 10001  →  X...X
 *   Row 2: 0x13 = 10011  →  X..XX  (the slash through the zero)
 *   Row 3: 0x15 = 10101  →  X.X.X
 *   Row 4: 0x19 = 11001  →  XX..X
 *   Row 5: 0x11 = 10001  →  X...X
 *   Row 6: 0x0E = 01110  →  .XXX.
 *
 * Only the characters actually needed by the ASI are included:
 * digits 0-9, letters used in labels (A,C,E,F,H,I,K,L,M,O,S,T,V),
 * and punctuation (period, space, plus, minus).
 *
 * FONT_W and FONT_H define the glyph cell size in pixels. These are
 * used by the rendering functions to compute character spacing and
 * rotation centers.
 */
#define FONT_W 5
#define FONT_H 7

static const struct { char ch; uint8_t r[7]; } glyphs[] = {
    {'0', {0x0E,0x11,0x13,0x15,0x19,0x11,0x0E}},
    {'1', {0x04,0x0C,0x04,0x04,0x04,0x04,0x0E}},
    {'2', {0x0E,0x11,0x01,0x02,0x04,0x08,0x1F}},
    {'3', {0x1F,0x02,0x04,0x02,0x01,0x11,0x0E}},
    {'4', {0x02,0x06,0x0A,0x12,0x1F,0x02,0x02}},
    {'5', {0x1F,0x10,0x1E,0x01,0x01,0x11,0x0E}},
    {'6', {0x06,0x08,0x10,0x1E,0x11,0x11,0x0E}},
    {'7', {0x1F,0x01,0x02,0x04,0x08,0x08,0x08}},
    {'8', {0x0E,0x11,0x11,0x0E,0x11,0x11,0x0E}},
    {'9', {0x0E,0x11,0x11,0x0F,0x01,0x02,0x0C}},
    {'A', {0x0E,0x11,0x11,0x1F,0x11,0x11,0x11}},
    {'C', {0x0E,0x11,0x10,0x10,0x10,0x11,0x0E}},
    {'E', {0x1F,0x10,0x10,0x1E,0x10,0x10,0x1F}},
    {'F', {0x1F,0x10,0x10,0x1E,0x10,0x10,0x10}},
    {'H', {0x11,0x11,0x11,0x1F,0x11,0x11,0x11}},
    {'I', {0x0E,0x04,0x04,0x04,0x04,0x04,0x0E}},
    {'K', {0x11,0x12,0x14,0x18,0x14,0x12,0x11}},
    {'L', {0x10,0x10,0x10,0x10,0x10,0x10,0x1F}},
    {'M', {0x11,0x1B,0x15,0x15,0x11,0x11,0x11}},
    {'O', {0x0E,0x11,0x11,0x11,0x11,0x11,0x0E}},
    {'S', {0x0E,0x11,0x10,0x0E,0x01,0x11,0x0E}},
    {'T', {0x1F,0x04,0x04,0x04,0x04,0x04,0x04}},
    {'V', {0x11,0x11,0x11,0x11,0x0A,0x0A,0x04}},
    {'.', {0x00,0x00,0x00,0x00,0x00,0x0C,0x0C}},
    {' ', {0x00,0x00,0x00,0x00,0x00,0x00,0x00}},
    {'+', {0x00,0x04,0x04,0x1F,0x04,0x04,0x00}},
    {'-', {0x00,0x00,0x00,0x1F,0x00,0x00,0x00}},
};
#define N_GLYPHS ((int)(sizeof(glyphs)/sizeof(glyphs[0])))

/*
 * font_lookup -- Find the bitmap row data for a given ASCII character.
 *
 * Performs a linear search through the glyph table. With only ~27
 * entries this is perfectly fast. Returns NULL if the character is
 * not in the font (caller should skip rendering for that character).
 */
static const uint8_t *font_lookup(char c)
{
    for (int i = 0; i < N_GLYPHS; i++)
        if (glyphs[i].ch == c) return glyphs[i].r;
    return NULL;
}

/* ================================================================== */
/*  Rotated character rendering                                       */
/* ================================================================== */
/*
 * draw_rotated_char -- Render a single bitmap font character at an
 * arbitrary position and rotation angle.
 *
 * This is the core text rendering primitive for the circular dial face.
 * Speed numbers like "100", "200", "350" must be drawn along the
 * tangent of the dial at their respective angular positions, so each
 * character needs to be rotated to match the local tangent direction.
 *
 * Algorithm:
 *   1. Look up the 5x7 bitmap for the character.
 *   2. For each set pixel in the bitmap, compute its position in
 *      "local" coordinates relative to the character's center:
 *        lx = col*scale + sx - hw   (horizontal offset from center)
 *        ly = row*scale + sy - hh   (vertical offset from center)
 *      where hw,hh are half the total character width/height in pixels.
 *   3. Apply 2D rotation using the standard rotation matrix:
 *        px = fcx + lx*cos(a) - ly*sin(a)
 *        py = fcy + lx*sin(a) + ly*cos(a)
 *   4. Write the pixel color to the framebuffer if within bounds.
 *
 * Parameters:
 *   fb         -- pointer to the framebuffer (ARGB8888 pixels)
 *   stride     -- framebuffer width in pixels (for row stride calc)
 *   fcx, fcy   -- screen position for the CENTER of the character
 *   c          -- ASCII character to draw
 *   angle_rad  -- rotation angle in radians (0 = upright, positive = CW)
 *   color      -- 0xAARRGGBB pixel color
 *   scale      -- integer scale factor (1 = native 5x7, 2 = 10x14, etc.)
 *
 * The 'scale' parameter works by iterating (sx, sy) over a scale x scale
 * sub-pixel grid for each font pixel, effectively magnifying the glyph.
 * Scale=2 is used for the dial numbers, scale=3 for the Mach drum.
 *
 * The bounds check uses unsigned comparison trick: casting to unsigned
 * makes negative values wrap to large positive values, so a single
 * comparison handles both <0 and >=MAX.
 */
static void draw_rotated_char(uint32_t *fb, int stride, int fcx, int fcy,
                               char c, float angle_rad, uint32_t color, int scale)
{
    const uint8_t *bits = font_lookup(c);
    if (!bits) return;
    float cs = cosf(angle_rad), sn = sinf(angle_rad);
    /* Half-width and half-height of the scaled character cell, used
     * to center the glyph on (fcx, fcy) rather than placing the
     * top-left corner there. */
    float hw = (FONT_W * scale) / 2.0f;
    float hh = (FONT_H * scale) / 2.0f;

    for (int row = 0; row < FONT_H; row++)
        for (int col = 0; col < FONT_W; col++) {
            /* Test if this pixel is set in the bitmap.
             * Bit 4 (0x10) = leftmost column, bit 0 = rightmost.
             * The expression (0x10 >> col) selects the correct bit. */
            if (!(bits[row] & (0x10 >> col))) continue;
            /* Iterate over the scale x scale sub-pixel block to
             * magnify the glyph. For scale=1 this is just one pixel. */
            for (int sy = 0; sy < scale; sy++)
                for (int sx = 0; sx < scale; sx++) {
                    /* Local coordinates relative to character center */
                    float lx = col*scale + sx - hw;
                    float ly = row*scale + sy - hh;
                    /* Apply 2D rotation matrix and translate to screen */
                    int px = (int)(fcx + lx*cs - ly*sn + 0.5f);
                    int py = (int)(fcy + lx*sn + ly*cs + 0.5f);
                    /* Unsigned bounds check (see note above) */
                    if ((unsigned)px < DISP_W && (unsigned)py < DISP_H)
                        fb[py*stride+px] = color;
                }
        }
}

/* ================================================================== */
/*  Dial-tangent text rendering                                       */
/* ================================================================== */
/*
 * draw_dial_text -- Render a text string along the tangent of the
 * circular dial at a given angular position.
 *
 * This function is used for the speed number labels ("60", "100",
 * "200", etc.) and the "IAS", "KT", and "MACH" legends. Each
 * character in the string is individually rotated so that the text
 * appears to follow the curve of the dial, always readable from
 * the outside (like numbers on a clock face).
 *
 * Coordinate system:
 *   Angles are measured in degrees clockwise from 12 o'clock.
 *   0 degrees = straight up (12 o'clock).
 *   90 degrees = 3 o'clock.
 *   180 degrees = 6 o'clock.
 *   270 degrees = 9 o'clock.
 *
 *   The position on the dial is computed using:
 *     x = CX + radius * sin(angle)
 *     y = CY - radius * cos(angle)
 *   (Note: sin for X and -cos for Y because 0 degrees is UP, not RIGHT.)
 *
 * Text orientation:
 *   The text is rotated so that it reads along the tangent direction
 *   at the given angle. However, for angles in the bottom half of
 *   the dial (90-270 degrees), the text would appear upside-down
 *   if simply rotated by the dial angle. So we flip it by adding
 *   180 degrees to the rotation, making it always readable from
 *   outside the dial. This is exactly how numbers are printed on
 *   a real mechanical instrument dial.
 *
 * Character spacing:
 *   Characters are spaced along the tangent direction (not along
 *   an arc). For the radius and character sizes involved, the
 *   difference between tangential and arc spacing is negligible.
 *   Each character is offset from center by:
 *     offset = (i - (len-1)/2) * spacing
 *   This centers the string on the dial position.
 *
 * Parameters:
 *   fb, stride  -- framebuffer and its width
 *   angle_deg   -- angular position on the dial (degrees CW from 12)
 *   radius      -- radial distance from dial center to text center
 *   text        -- null-terminated string to draw
 *   color       -- 0xAARRGGBB pixel color
 *   scale       -- font scale factor (passed to draw_rotated_char)
 */
static void draw_dial_text(uint32_t *fb, int stride, float angle_deg,
                            float radius, const char *text, uint32_t color, int scale)
{
    float angle_rad = angle_deg * (float)M_PI / 180.0f;
    /* Compute the screen position on the dial at the given angle/radius.
     * sin(angle) gives the X component, -cos(angle) gives Y, because
     * angle=0 means "straight up" (12 o'clock). */
    int tcx = CX + (int)(radius * sinf(angle_rad));
    int tcy = CY - (int)(radius * cosf(angle_rad));

    /* Text rotation: tangent to the dial, readable from outside.
     * The tangent direction at angle 'a' is (cos(a), sin(a)) in
     * our screen coordinate system. */
    float text_rot = angle_rad;
    float tang_x = cosf(angle_rad);
    float tang_y = sinf(angle_rad);

    /* Flip text 180 degrees for the bottom half of the dial so it
     * doesn't appear upside-down. On a real instrument, numbers in
     * the lower half of the dial are printed "right-side up" when
     * viewed from outside the dial. */
    if (angle_deg < 0) { angle_deg += 360; }
    if (angle_deg > 90 && angle_deg < 270) {
        text_rot += (float)M_PI;    /* rotate text 180 degrees */
        tang_x = -tang_x;           /* reverse tangent for spacing */
        tang_y = -tang_y;
    }

    int len = (int)strlen(text);
    float spacing = (FONT_W + 1) * scale;  /* pixels between char centers */

    /* Draw each character, offset along the tangent direction from
     * the center point. The expression (i - (len-1)/2.0f) produces
     * a symmetric range: for a 3-char string, offsets are -1, 0, +1. */
    for (int i = 0; i < len; i++) {
        float offset = (i - (len - 1) / 2.0f) * spacing;
        int ccx = tcx + (int)(offset * tang_x);
        int ccy = tcy + (int)(offset * tang_y);
        draw_rotated_char(fb, stride, ccx, ccy, text[i], text_rot, color, scale);
    }
}

/* ================================================================== */
/*  Non-rotated flat text (for the control panel)                     */
/* ================================================================== */
/*
 * These are simpler text rendering functions used only in the control
 * panel area below the instrument face. They render at a fixed 2x
 * scale with no rotation (always horizontal). Reused from the other
 * instrument host programs (altimeter, VSI, etc.) for visual
 * consistency across the simulator suite.
 */
static void draw_char_flat(uint32_t *fb, int x, int y, char c, uint32_t color)
{
    const uint8_t *bits = font_lookup(c);
    if (!bits) return;
    for (int row=0;row<FONT_H;row++)
        for (int col=0;col<FONT_W;col++)
            if (bits[row] & (0x10>>col))
                /* 2x scale: each font pixel becomes a 2x2 block */
                for (int sy=0;sy<2;sy++) for (int sx=0;sx<2;sx++){
                    int px=x+col*2+sx, py=y+row*2+sy;
                    if((unsigned)px<WIN_W&&(unsigned)py<WIN_H)
                        fb[py*WIN_W+px]=color;
                }
}
static void draw_str_flat(uint32_t *fb, int x, int y, const char *s, uint32_t color)
{ while(*s){draw_char_flat(fb,x,y,*s++,color);x+=12;} }
/* Center-aligned variant: computes total string width, then offsets */
static void draw_str_cx_flat(uint32_t *fb, int cx, int y, const char *s, uint32_t color)
{ int tw=(int)strlen(s)*12-2; draw_str_flat(fb,cx-tw/2,y,s,color); }

/* ================================================================== */
/*  GUI helpers (control panel buttons and hit testing)               */
/* ================================================================== */

/* fill_rect -- Solid rectangle fill with bounds checking. */
static void fill_rect(uint32_t *fb, int rx, int ry, int rw, int rh, uint32_t c)
{
    for(int y=ry;y<ry+rh;y++){if((unsigned)y>=WIN_H) continue;
    for(int x=rx;x<rx+rw;x++) if((unsigned)x<WIN_W) fb[y*WIN_W+x]=c;}
}

/*
 * draw_arrow_btn -- Draw a triangular arrow inside a button rectangle.
 *
 * The arrow is drawn as a filled triangle pointing left (dir < 0) or
 * right (dir > 0). The triangle is constructed row by row: for each
 * row, the width is proportional to the distance from the midpoint,
 * creating a diamond/arrow shape. The 'pad' inset keeps the arrow
 * from touching the button edges.
 */
static void draw_arrow_btn(uint32_t *fb, int bx, int by, int bw, int bh,
                            int dir, uint32_t color)
{
    int pad=9,th=bh-2*pad,tw=bw-2*pad,half=th/2;
    if(th<2||tw<2)return;
    for(int row=0;row<th;row++){
        int w=tw*(half-abs(row-half))/half; if(w<1)w=1;
        int y=by+pad+row,x0=(dir<0)?bx+bw-pad-w:bx+pad;
        for(int c2=0;c2<w;c2++) if((unsigned)(x0+c2)<WIN_W&&(unsigned)y<WIN_H)
            fb[y*WIN_W+x0+c2]=color;
    }
}

/*
 * draw_button -- Render a complete button with background color
 * (idle/hover/pressed) and an arrow glyph inside.
 */
static void draw_button(uint32_t *fb, int bx, int by, int dir, int hover, int press)
{
    uint32_t bg=press?COL_BTN_PRESS:hover?COL_BTN_HOVER:COL_BTN_NORMAL;
    fill_rect(fb,bx,by,BTN_W,BTN_H,bg);
    draw_arrow_btn(fb,bx,by,BTN_W,BTN_H,dir,COL_ARROW_C);
}

/*
 * hit_test -- Determine which button (if any) the mouse is over.
 *
 * Returns a button index 0..5 (3 groups x 2 buttons), or -1 if the
 * mouse is not over any button. Button indices:
 *   0 = IAS left (decrease)    1 = IAS right (increase)
 *   2 = MACH left (decrease)   3 = MACH right (increase)
 *   4 = VMO left (decrease)    5 = VMO right (increase)
 */
#define N_BUTTONS (N_CONTROLS*2)
static int hit_test(int mx, int my)
{
    for(int i=0;i<N_BUTTONS;i++){
        int g=i/2,is_r=i&1;
        int bx=is_r?BTN_R_X(g):BTN_L_X(g);
        if(mx>=bx&&mx<bx+BTN_W&&my>=BTN_Y&&my<BTN_Y+BTN_H) return i;
    }
    return -1;
}

/* ================================================================== */
/*  Non-linear airspeed scale -- the heart of the ASI                 */
/* ================================================================== */
/*
 * THE NON-LINEAR AIRSPEED SCALE
 *
 * A real airspeed indicator has a fundamentally non-linear scale.
 * This is because airspeed is derived from dynamic pressure (q),
 * and the relationship between indicated airspeed and dynamic
 * pressure is:
 *
 *   IAS = sqrt(2 * q / rho_0)
 *
 * ...which means the pressure difference between 60 kts and 80 kts
 * is much smaller than between 400 kts and 420 kts. On a mechanical
 * ASI, the aneroid capsule deflection is roughly proportional to
 * pressure, so the pointer moves more degrees per knot at low speeds
 * than at high speeds.
 *
 * The Gulfstream ASI exaggerates this further with a shaped cam in
 * the mechanism. The result is the characteristic "stretched low end"
 * dial where:
 *   - 60 to 200 kts spans about 177 degrees (nearly half the dial)
 *   - 200 to 500 kts spans about 150 degrees (compressed into the
 *     remaining arc)
 *
 * This gives pilots excellent resolution in the critical flight
 * regimes (approach: 120-180 kts) while still fitting the full
 * operating range (up to 500 kts / Mach 0.94) on one dial.
 *
 * SCALE TABLE
 *
 * The asi_scale[] table below maps specific airspeed values (in knots)
 * to angular positions (in degrees clockwise from 12 o'clock). These
 * calibration points were measured from a photograph of the actual
 * Gulfstream ASI dial face.
 *
 * Convention: 0 degrees = 12 o'clock (straight up).
 *             90 degrees = 3 o'clock.
 *             180 degrees = 6 o'clock.
 *             Increasing angle = clockwise rotation.
 *
 * Key calibration points:
 *   60 kts  =   3 degrees  (just past 12 o'clock -- this is the
 *                            lowest marked speed on the dial)
 *   200 kts = 180 degrees  (6 o'clock -- the halfway point)
 *   400 kts = 300 degrees  (10 o'clock -- deep into the compressed
 *                            high-speed region)
 *   500 kts = 330 degrees  (11 o'clock -- near the top, maximum
 *                            indicated airspeed)
 *
 * Between these calibration points, the scale is nearly linear, so
 * simple piecewise linear interpolation in kts_to_deg() produces a
 * smooth, accurate dial that closely matches the real instrument.
 *
 * Note: Real Gulfstream ASIs start at 60 kts because the aircraft
 * has no useful aerodynamic indications below that speed. The first
 * mark on the dial is 60, not 0.
 */

/* Angles in degrees CW from 12 o'clock.
 * Calibrated: 60kt=3deg(12 o'clock), 200kt=180deg(6 o'clock), 400kt=300deg(10 o'clock) */
typedef struct { float kts; float deg; } AsiScale;
static const AsiScale asi_scale[] = {
    {  60,   3 }, {  80,  28 }, { 100,  55 },
    { 120,  80 }, { 140, 105 }, { 160, 130 },
    { 180, 155 }, { 200, 180 }, { 230, 213 },
    { 250, 235 }, { 300, 262 }, { 350, 282 },
    { 400, 300 }, { 450, 316 }, { 500, 330 },
};
#define ASI_N (sizeof(asi_scale)/sizeof(asi_scale[0]))

/*
 * kts_to_deg -- Convert an airspeed in knots to a dial angle in degrees.
 *
 * Uses piecewise linear interpolation between the calibration points
 * in asi_scale[]. For an input speed between two adjacent table
 * entries, the angle is computed by linear interpolation:
 *
 *   t = (kts - kts_lo) / (kts_hi - kts_lo)     // fractional position
 *   deg = deg_lo + t * (deg_hi - deg_lo)         // interpolated angle
 *
 * This is the fundamental mapping function used by EVERYTHING that
 * needs to place something at a specific airspeed on the dial:
 *   - Tick marks (major and minor)
 *   - Speed number labels
 *   - The IAS pointer
 *   - The VMO barber-pole pointer
 *
 * Edge behavior: speeds at or below 60 kts clamp to 3 degrees;
 * speeds at or above 500 kts clamp to 330 degrees.
 */
static float kts_to_deg(float kts)
{
    /* Clamp to the table endpoints */
    if (kts <= asi_scale[0].kts) return asi_scale[0].deg;
    if (kts >= asi_scale[ASI_N-1].kts) return asi_scale[ASI_N-1].deg;
    /* Search for the enclosing table segment */
    for (int i = 0; i < (int)ASI_N-1; i++) {
        if (kts >= asi_scale[i].kts && kts <= asi_scale[i+1].kts) {
            /* Fractional position within this segment (0.0 to 1.0) */
            float t = (kts - asi_scale[i].kts) / (asi_scale[i+1].kts - asi_scale[i].kts);
            /* Linear interpolation of the angle */
            return asi_scale[i].deg + t * (asi_scale[i+1].deg - asi_scale[i].deg);
        }
    }
    return 0;   /* Should never be reached */
}

/* ================================================================== */
/*  Dial face rendering (pre-rendered once at startup)                */
/* ================================================================== */
/*
 * The dial face contains all the STATIC elements of the instrument:
 *   - The black face background with dark bezel ring
 *   - All tick marks (major and minor)
 *   - All speed number labels (60, 80, 100, ..., 400)
 *   - The "IAS" and "KT" text legends
 *
 * This is rendered once into a dedicated buffer (dial_bg) at startup,
 * then memcpy'd into the active framebuffer each frame. This avoids
 * recomputing hundreds of sin/cos calls, font lookups, and tick
 * rendering operations every frame. Only the dynamic elements
 * (pointers, Mach drum, flags, hub) are drawn per-frame.
 */

/*
 * draw_tick -- Render a single radial tick mark on the dial.
 *
 * A tick mark is a short radial line segment extending outward from
 * r_inner to r_outer at a given angle. The 'width' parameter controls
 * thickness perpendicular to the radial direction.
 *
 * The tick is drawn by stepping along the radial direction (r loop)
 * and at each radial position, drawing 'width' pixels perpendicular
 * to the radius. The perpendicular direction is (cos(angle), sin(angle))
 * -- rotated 90 degrees from the radial direction (sin, -cos).
 *
 * Parameters:
 *   angle_deg  -- angular position in degrees CW from 12 o'clock
 *   r_inner    -- starting radius (closer to center)
 *   r_outer    -- ending radius (closer to dial edge)
 *   width      -- thickness in pixels (1 for minor, 2 for major)
 *   color      -- pixel color (white for major, gray for minor)
 */
static void draw_tick(uint32_t *fb, int stride, float angle_deg,
                       int r_inner, int r_outer, int width, uint32_t color)
{
    float rad = angle_deg * (float)M_PI / 180.0f;
    float sx = sinf(rad), cx = cosf(rad);
    /* Step outward along the radial direction from r_inner to r_outer */
    for (int r = r_inner; r <= r_outer; r++) {
        /* Center pixel position on the radial line */
        int px_c = CX + (int)(r * sx + 0.5f);
        int py_c = CY - (int)(r * cx + 0.5f);
        /* Draw perpendicular thickness centered on the radial line.
         * The perpendicular direction is (cos, sin) -- 90 degrees
         * rotated from the radial direction (sin, -cos). */
        for (int w = -width/2; w <= width/2; w++) {
            int px = px_c + (int)(w * cx + 0.5f);
            int py = py_c + (int)(w * sx + 0.5f);
            if ((unsigned)px < DISP_W && (unsigned)py < DISP_H)
                fb[py*stride+px] = color;
        }
    }
}

/*
 * render_dial_face -- Build the complete static dial face.
 *
 * This function populates a framebuffer with the entire static
 * instrument face: background, bezel, tick marks, numbers, and
 * labels. It is called exactly once at startup.
 *
 * BACKGROUND RENDERING:
 *   The face has three concentric zones:
 *   - Beyond DIAL_R+20: pure black (window background, outside bezel)
 *   - DIAL_R+5 to DIAL_R+20: dark gray bezel ring (simulates the
 *     raised metal bezel that holds the glass on a real instrument)
 *   - Inside DIAL_R+5: very dark gray face (0x0A0A0A -- not pure
 *     black, to give a slight sense of depth)
 *
 * TICK MARK GRADUATION SCHEME:
 *   The tick marks faithfully reproduce the graduation pattern of the
 *   real Gulfstream ASI, which varies across the speed range:
 *
 *   60-80 kts:    Major ticks at 60 and 80.
 *                 Minor ticks every 5 kts (4 minor ticks between majors).
 *                 This is the lowest range; 5-knot resolution is adequate.
 *
 *   80-230 kts:   Major ticks every 10 kts (both labeled like 80, 100,
 *                 120... and unlabeled like 90, 110, 130...).
 *                 Minor ticks every 2 kts (4 minor ticks between each
 *                 pair of 10-knot major ticks).
 *                 This is the primary operating range. 2-knot minor
 *                 tick resolution lets the pilot read approach speed
 *                 (Vref) to within 1 knot by interpolation.
 *
 *   230-250 kts:  Transitional range. Major tick at 240, minors every
 *                 2 kts. This continues the fine resolution through
 *                 the end of the expanded region.
 *
 *   250-500 kts:  Major ticks at labeled values (250, 300, 350, 400)
 *                 plus unlabeled majors at 450, 500.
 *                 Minor ticks every 10 kts (4 minor ticks between
 *                 each 50-knot major). The scale is compressed here,
 *                 so 10-knot minor ticks are appropriate.
 *
 *   The key insight: the tick density decreases as airspeed increases,
 *   matching the compression of the non-linear scale. This keeps the
 *   visual spacing of tick marks roughly uniform around the dial.
 *
 * LABELS:
 *   "IAS" and "KT" are drawn near 6 o'clock (160 and 172 degrees)
 *   inside the tick ring, identifying the instrument type and units.
 */
static void render_dial_face(uint32_t *fb, int stride)
{
    uint32_t white = 0xFFDDDDDDu;  /* off-white for major ticks and numbers */
    uint32_t gray  = 0xFFAAAAAAu;  /* medium gray for minor ticks */

    /* Black background circle with bezel ring.
     * Three concentric zones computed per-pixel using distance-squared
     * from the dial center. Using distance-squared avoids a sqrt(). */
    for (int y = 0; y < DISP_H; y++)
        for (int x = 0; x < DISP_W; x++) {
            float dx = x - CX, dy = y - CY;
            float dsq = dx*dx + dy*dy;
            if (dsq > (DIAL_R+20)*(DIAL_R+20))
                fb[y*stride+x] = 0xFF000000u;      /* outside bezel: black */
            else if (dsq > (DIAL_R+5)*(DIAL_R+5))
                fb[y*stride+x] = 0xFF222222u;       /* bezel ring: dark gray */
            else
                fb[y*stride+x] = 0xFF0A0A0Au;       /* dial face: near-black */
        }

    /* Draw tick marks.
     * Major and minor share same inner radius.
     * Major = 2x length, 2x width of minor.
     *
     * Graduation scheme (from the real instrument):
     *   60-80:  major at 60,80; minor every 5 kts (4 minors between)
     *   80-200: major every 10 kts; minor every 2 kts (4 minors between)
     *   200+:   major at labeled values; minor every 5 or 10 kts */

    /* Labeled major tick positions -- these are the speeds that get
     * both a major tick mark AND a printed number on the dial. */
    static const int labels[] = {60,80,100,120,140,160,180,200,230,250,300,350,400};
    int n_labels = 13;

    /* Pass 1: Major ticks with numbers.
     * For each labeled speed, draw a major tick mark and the speed
     * number at the NUM_R radius. The number is drawn using
     * draw_dial_text which handles tangent-aligned rotation. */
    for (int i = 0; i < n_labels; i++) {
        float deg = kts_to_deg((float)labels[i]);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MAJ, 2, white);
        char num[5];
        snprintf(num, sizeof(num), "%d", labels[i]);
        draw_dial_text(fb, stride, deg, NUM_R, num, white, 2);
    }

    /* Pass 2: Minor ticks -- different intervals for different ranges */

    /* 60-80 kts: minor ticks every 5 kts.
     * At these low speeds, the scale is most expanded -- each 5-knot
     * interval is about 6.25 degrees. Minor ticks at 65, 70, 75. */
    for (int kts = 65; kts < 80; kts += 5) {
        float deg = kts_to_deg((float)kts);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MIN, 1, gray);
    }

    /* 80-230 kts: unlabeled major ticks at every 10 kts (90,110,...,190,210,220).
     * These are full-length ticks without numbers, providing a clear
     * 10-knot grid in the primary operating range. The loop skips any
     * value that already has a labeled major tick. */
    for (int kts = 90; kts <= 220; kts += 10) {
        /* Skip if already labeled */
        int skip = 0;
        for (int i = 0; i < n_labels; i++)
            if (kts == labels[i]) { skip = 1; break; }
        if (skip) continue;
        float deg = kts_to_deg((float)kts);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MAJ, 2, white);
    }

    /* 80-230 kts: minor ticks every 2 kts.
     * This gives 4 minor ticks between each 10-knot major tick,
     * allowing the pilot to read speed to 2-knot accuracy by
     * counting ticks. Skips the major tick positions (multiples
     * of 10) to avoid overdrawing. */
    for (int kts = 82; kts < 230; kts += 2) {
        if (kts % 10 == 0) continue;   /* skip major positions */
        float deg = kts_to_deg((float)kts);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MIN, 1, gray);
    }

    /* 230-250 kts: transitional range.
     * An unlabeled major tick at 240 kts, with 2-knot minors continuing
     * the fine resolution from the 80-230 range. */
    {
        float deg = kts_to_deg(240.0f);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MAJ, 2, white);
    }
    for (int kts = 232; kts < 250; kts += 2) {
        if (kts % 10 == 0) continue;
        float deg = kts_to_deg((float)kts);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MIN, 1, gray);
    }

    /* 250-500 kts: compressed high-speed range.
     * Unlabeled major ticks at 450 and 500 kts. The 250, 300, 350, and
     * 400 marks were already drawn in Pass 1 with numbers. */
    for (int kts = 450; kts <= 500; kts += 50) {
        float deg = kts_to_deg((float)kts);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MAJ, 2, white);
    }

    /* 250-500 kts: minor ticks every 10 kts.
     * In this compressed range, 10-knot resolution is the finest
     * practical graduation. There are 4 minor ticks between each
     * 50-knot major tick. */
    for (int kts = 260; kts <= 490; kts += 10) {
        if (kts % 50 == 0) continue;   /* skip major positions */
        float deg = kts_to_deg((float)kts);
        draw_tick(fb, stride, deg, TICK_INNER, TICK_INNER + TICK_MIN, 1, gray);
    }

    /* Instrument identification legends.
     * "IAS" = Indicated Air Speed (the type of speed measurement).
     * "KT"  = Knots (the unit of measurement).
     * Drawn at about the 5-6 o'clock position, inside the tick ring,
     * at a radius of 90 pixels from center. Scale=2 for readability. */
    draw_dial_text(fb, stride, 160, 90, "IAS", gray, 2);
    draw_dial_text(fb, stride, 172, 90, "KT", gray, 2);
}

/* ================================================================== */
/*  Dynamic rendering (per frame)                                     */
/* ================================================================== */
/*
 * Everything below is drawn EVERY FRAME on top of the pre-rendered
 * static dial face. The draw order matters:
 *
 *   1. Mach drum display (behind everything else)
 *   2. OFF/VMO flag
 *   3. VMO barber-pole pointer (behind IAS pointer)
 *   4. IAS pointer (on top -- the primary indication)
 *   5. Center hub (covers the base of both pointers)
 *
 * This layering matches the real instrument, where the IAS pointer
 * physically sits on top of the VMO pointer, and both pivot around
 * a central hub cap.
 */

/* ================================================================== */
/*  IAS pointer (the primary airspeed needle)                         */
/* ================================================================== */
/*
 * draw_ias_pointer -- Draw the main indicated airspeed pointer.
 *
 * This is a white needle with a thin shaft and an arrowhead tip,
 * matching the appearance of the IAS pointer on a real Gulfstream ASI.
 *
 * The pointer has two parts:
 *
 *   1. MAIN SHAFT (radius 30 to PTR_LEN=170):
 *      A thin line, 3 pixels wide (w = -1 to +1), extending from
 *      near the center hub outward. It starts at r=30 (just outside
 *      the hub radius of 18) to leave room for the hub cap overlay.
 *
 *   2. ARROW TIP (last 15 pixels of the pointer, radius PTR_LEN-15
 *      to PTR_LEN):
 *      A filled triangle that tapers from 13 pixels wide (half_w=6,
 *      so 6+1+6=13) down to a single pixel at the very tip. The
 *      taper is linear: at the base of the arrowhead (r = PTR_LEN-15),
 *      the half-width is 6 pixels; at the tip (r = PTR_LEN), the
 *      half-width is 0.
 *
 *      The taper fraction is computed as:
 *        frac = (r - (PTR_LEN - 15)) / 15.0
 *      which goes from 0.0 at the base to 1.0 at the tip. The
 *      half-width is then:
 *        half_w = 6 * (1 - frac)
 *
 * Both parts use the same rendering technique: step along the radial
 * direction (the pointer's axis) and at each step, draw a horizontal
 * bar of pixels perpendicular to the pointer. The perpendicular
 * direction is (cos(angle), sin(angle)), while the radial direction
 * is (sin(angle), -cos(angle)).
 *
 * The pointer overwrites whatever was previously drawn at those pixel
 * positions (no alpha blending), which is fine because it should be
 * opaque and sit on top of everything except the center hub.
 */
static void draw_ias_pointer(uint32_t *fb, int stride, float angle_deg)
{
    float rad = angle_deg * (float)M_PI / 180.0f;
    float sx = sinf(rad), cx = cosf(rad);   /* radial direction: (sx, -cx) */
    uint32_t white = 0xFFEEEEEEu;           /* slightly off-white */

    /* Main shaft: thin 3-pixel-wide line from r=30 to r=PTR_LEN */
    for (int r = 30; r <= PTR_LEN; r++) {
        int px_c = CX + (int)(r * sx);      /* center of shaft at this radius */
        int py_c = CY - (int)(r * cx);
        for (int w = -1; w <= 1; w++) {      /* 3 pixels wide perpendicular */
            int px = px_c + (int)(w * cx);   /* perpendicular offset */
            int py = py_c + (int)(w * sx);
            if ((unsigned)px < DISP_W && (unsigned)py < DISP_H)
                fb[py*stride+px] = white;
        }
    }

    /* Arrow tip: filled triangle tapering to a point.
     * The arrowhead occupies the last 15 pixels of the pointer length.
     * At the base (r = PTR_LEN - 15), it's 13 pixels wide.
     * At the tip (r = PTR_LEN), it narrows to ~1 pixel. */
    for (int r = PTR_LEN - 15; r <= PTR_LEN; r++) {
        /* frac goes from 0.0 (base) to 1.0 (tip) */
        float frac = (float)(r - (PTR_LEN-15)) / 15.0f;
        /* half_w linearly decreases from 6 to 0 */
        int half_w = (int)(6.0f * (1.0f - frac));
        int px_c = CX + (int)(r * sx);
        int py_c = CY - (int)(r * cx);
        /* Fill the perpendicular cross-section at this radius */
        for (int w = -half_w; w <= half_w; w++) {
            int px = px_c + (int)(w * cx);
            int py = py_c + (int)(w * sx);
            if ((unsigned)px < DISP_W && (unsigned)py < DISP_H)
                fb[py*stride+px] = white;
        }
    }
}

/* ================================================================== */
/*  VMO barber-pole pointer                                           */
/* ================================================================== */
/*
 * draw_vmo_pointer -- Draw the VMO (Maximum Operating Velocity)
 * barber-pole pointer.
 *
 * On the real Gulfstream ASI, the VMO pointer is a distinctive
 * red-and-white diagonally-striped needle (the "barber pole"). It is
 * driven by the Air Data Computer and rotates to indicate the current
 * VMO limit, which varies with altitude. When the IAS pointer reaches
 * or exceeds the VMO pointer, the pilot is approaching (or has
 * exceeded) the maximum safe operating speed for the current altitude.
 *
 * BARBER-POLE STRIPE PATTERN:
 *   The diagonal red/white stripes are generated using modular
 *   arithmetic on the pixel coordinates within the pointer. For each
 *   pixel at radial position 'r' and perpendicular offset 'w':
 *
 *     stripe = ((r + w + 1000) / 5) % 2
 *
 *   Breaking this down:
 *     - (r + w) creates diagonal lines at 45 degrees along the
 *       pointer body. Pixels where (r+w) has the same value lie on
 *       a diagonal line running from lower-left to upper-right
 *       (relative to the pointer axis).
 *     - Adding 1000 ensures the dividend is always positive, avoiding
 *       platform-dependent behavior of integer division with negative
 *       operands. (Without this, negative r+w values could produce
 *       unexpected stripe boundaries on some compilers.)
 *     - Dividing by 5 sets the stripe width: each colored band is
 *       5 pixels wide.
 *     - Modulo 2 alternates between two states: 0 = white, 1 = red.
 *
 *   The result is the classic barber-pole appearance: alternating
 *   red (0xFFDD2222) and white (0xFFEEEEEE) diagonal bands, 5 pixels
 *   wide, running at 45 degrees to the pointer axis.
 *
 * POINTER GEOMETRY:
 *   The VMO pointer is slightly shorter than the IAS pointer and has
 *   a gradual taper at the tip:
 *     - Starts at r=40 (further from center than IAS pointer's r=30)
 *     - Ends at r=PTR_LEN-5 (=165, shorter than IAS pointer's 170)
 *     - Body width: 7 pixels (half_w=3, so -3 to +3)
 *     - Taper zone: last 15 pixels (r > PTR_LEN-20 to PTR_LEN-5)
 *       narrows from 7px to 3px
 *
 *   Being drawn BEFORE the IAS pointer in the render order, the VMO
 *   pointer appears behind it when they overlap, matching the real
 *   instrument where the IAS needle physically sits on top.
 */
static void draw_vmo_pointer(uint32_t *fb, int stride, float angle_deg)
{
    float rad = angle_deg * (float)M_PI / 180.0f;
    float sx = sinf(rad), cx = cosf(rad);

    for (int r = 40; r <= PTR_LEN - 5; r++) {
        int px_c = CX + (int)(r * sx);
        int py_c = CY - (int)(r * cx);
        int half_w = 3;     /* default body half-width: 3 (= 7px total) */

        /* Taper at tip: linearly reduce width over the last 15 pixels.
         * When r > PTR_LEN-20, frac goes from 1.0 down to ~0.0 at the
         * tip, shrinking half_w from 3 to 1. */
        if (r > PTR_LEN - 20) {
            float frac = (float)(PTR_LEN - 5 - r) / 15.0f;
            half_w = (int)(3.0f * frac) + 1;
        }

        for (int w = -half_w; w <= half_w; w++) {
            int px = px_c + (int)(w * cx);
            int py = py_c + (int)(w * sx);
            if ((unsigned)px >= DISP_W || (unsigned)py >= DISP_H) continue;

            /* Diagonal stripe pattern: alternating red/white bands.
             * See the detailed explanation in the function header above. */
            int stripe = ((r + w + 1000) / 5) % 2;
            fb[py*stride+px] = stripe ? 0xFFDD2222u : 0xFFEEEEEEu;
        }
    }
}

/* ================================================================== */
/*  Mach drum display window                                          */
/* ================================================================== */
/*
 * draw_mach_display -- Render the Mach number drum window.
 *
 * On a real Gulfstream ASI, there is a small rectangular cutout
 * (window) near the top of the dial face that reveals a mechanical
 * drum displaying the current Mach number. The drum is driven by
 * the Air Data Computer and shows values from .10 to .99.
 *
 * The Mach number is displayed as a decimal point followed by two
 * digits (e.g., ".84" for Mach 0.84). On the real instrument, the
 * individual digits are on separate rotating drums, so only the
 * ones digit scrolls smoothly while the tens digit steps. In this
 * simulation, we display the digits statically (no partial scroll
 * animation), which is acceptable for the host display.
 *
 * Layout:
 *   - Window position: top center of the dial (CX-30, CY-140)
 *   - Window size: 60x32 pixels
 *   - Background: very dark gray (0x111111) simulating the drum cavity
 *   - Border: medium gray (0x444444) simulating the window frame
 *   - Digits rendered at scale=3 (15x21 pixels per character)
 *   - "MACH" label drawn below the window using draw_dial_text
 *     at 0 degrees (12 o'clock) and radius 105, placing it just
 *     below the drum window
 *
 * The Mach value is converted to a two-digit integer (10-99), then
 * formatted as ".XX" for display. Values below .10 are clamped to
 * .10; values above .99 are clamped to .99.
 */
static void draw_mach_display(uint32_t *fb, int stride, float mach)
{
    /* Window position: top center of dial, just below 12 o'clock */
    int wx = CX - 30, wy = CY - 140;
    int ww = 60, wh = 32;

    /* Dark background (simulates the drum cavity behind the glass) */
    for (int y = wy; y < wy+wh; y++)
        for (int x = wx; x < wx+ww; x++)
            if ((unsigned)x < DISP_W && (unsigned)y < DISP_H)
                fb[y*stride+x] = 0xFF111111u;

    /* Border: thin 1-pixel frame around the window (top, bottom edges) */
    for (int x = wx; x < wx+ww; x++) {
        if ((unsigned)x < DISP_W) {
            if ((unsigned)wy < DISP_H) fb[wy*stride+x] = 0xFF444444u;
            if ((unsigned)(wy+wh-1) < DISP_H) fb[(wy+wh-1)*stride+x] = 0xFF444444u;
        }
    }
    /* Border: left and right edges */
    for (int y = wy; y < wy+wh; y++) {
        if ((unsigned)y < DISP_H) {
            if ((unsigned)wx < DISP_W) fb[y*stride+wx] = 0xFF444444u;
            if ((unsigned)(wx+ww-1) < DISP_W) fb[y*stride+wx+ww-1] = 0xFF444444u;
        }
    }

    /* Convert Mach number to two decimal digits.
     * mach=0.84 -> m100=84 -> d_tens=8, d_ones=4 -> display ".84" */
    int m100 = (int)(mach * 100 + 0.5f);   /* round to nearest integer */
    if (m100 < 10) m100 = 10;              /* clamp to .10 minimum */
    if (m100 > 99) m100 = 99;              /* clamp to .99 maximum */
    int d_tens = m100 / 10;                /* tens digit (0-9) */
    int d_ones = m100 % 10;                /* ones digit (0-9) */

    /* Format as ".XX" string */
    char txt[8];
    snprintf(txt, sizeof(txt), ".%d%d", d_tens, d_ones);
    /* Render centered in window using scale=3 (large digits) */
    int tx = wx + 8;
    int ty = wy + 5;
    for (int i = 0; txt[i]; i++) {
        draw_rotated_char(fb, stride, tx + i*14, ty + 10, txt[i], 0, 0xFFDDDDDDu, 3);
    }

    /* "MACH" label below the drum window.
     * Drawn at angle=0 (12 o'clock) at radius=105 from center,
     * which places it just below the drum window. Scale=1 for
     * a small, unobtrusive label. */
    draw_dial_text(fb, stride, 0, 105, "MACH", 0xFF999999u, 1);
}

/* ================================================================== */
/*  OFF / VMO warning flag                                            */
/* ================================================================== */
/*
 * draw_flag -- Render the instrument warning flag.
 *
 * Real aircraft instruments have mechanical flags that pop into view
 * in the dial window to alert the pilot of abnormal conditions:
 *
 *   "OFF" flag (orange background):
 *     Appears when the instrument has lost its input data (e.g.,
 *     the Air Data Computer has failed, or the Pitot-static system
 *     is unreliable). This tells the pilot the displayed airspeed
 *     should NOT be trusted. On the real instrument, this is a
 *     spring-loaded flag held out of view by a solenoid; when power
 *     or data is lost, the spring pushes it into the window.
 *
 *   "VMO" flag (red background):
 *     Appears when the indicated airspeed exceeds VMO. This is an
 *     overspeed warning that demands the pilot's immediate attention.
 *     On the real aircraft, this is accompanied by an aural warning
 *     ("clacker") and possible stick shaker activation.
 *
 *   No flag (hidden):
 *     When neither condition is active, the flag area is drawn as
 *     a dark rectangle matching the dial face, effectively invisible.
 *
 * The flag is positioned at (CX+40, CY+50) -- in the lower-right
 * quadrant of the dial, where it doesn't obscure the critical speed
 * numbers but is still clearly visible in the pilot's scan.
 *
 * Flag priority: VMO warning takes precedence over OFF. If both
 * conditions are simultaneously true, only VMO is shown, because
 * the overspeed condition is more immediately dangerous.
 *
 * The flag text is rendered at scale=1 using draw_rotated_char with
 * angle=0 (no rotation), producing small but readable text centered
 * in the flag rectangle.
 */
static void draw_flag(uint32_t *fb, int stride, int off_flag, int vmo_warning)
{
    int fx = CX + 40, fy = CY + 50;
    int fw = 38, fh = 18;

    uint32_t bg, fg;
    const char *txt;

    if (vmo_warning) {
        bg = 0xFFDD2222u; txt = "VMO"; fg = 0xFFFFFFFFu;   /* red + white text */
    } else if (off_flag) {
        bg = 0xFFDD3300u; txt = "OFF"; fg = 0xFFFFFFFFu;   /* orange + white text */
    } else {
        bg = 0xFF111111u; txt = ""; fg = 0xFF111111u;       /* hidden (dark) */
    }

    /* Fill flag background */
    for (int y = fy; y < fy+fh; y++)
        for (int x = fx; x < fx+fw; x++)
            if ((unsigned)x < DISP_W && (unsigned)y < DISP_H)
                fb[y*stride+x] = bg;

    /* Draw flag text (if any) centered in the rectangle */
    if (txt[0]) {
        int len = (int)strlen(txt);
        int tx = fx + fw/2;            /* horizontal center of flag */
        int ty2 = fy + fh/2;           /* vertical center of flag */
        float spacing = 8;             /* character spacing at scale=1 */
        for (int i = 0; i < len; i++) {
            int cx2 = tx + (int)((i - (len-1)/2.0f) * spacing);
            draw_rotated_char(fb, stride, cx2, ty2, txt[i], 0, fg, 1);
        }
    }
}

/* ================================================================== */
/*  Center hub                                                        */
/* ================================================================== */
/*
 * draw_hub -- Draw the center pivot hub that covers the base of both
 * pointers.
 *
 * On a real ASI, both the IAS and VMO pointers rotate around a
 * central pivot shaft, covered by a small metal hub cap. This hub
 * is drawn last (on top of both pointers) to cleanly cover where
 * the pointer bases converge at the center.
 *
 * RADIAL SHADING:
 *   The hub has a subtle radial gradient that simulates the convex
 *   shape of a real hub cap catching light. The shade formula is:
 *
 *     shade = 0.08 + 0.07 * (1.0 - distance/HUB_R)
 *
 *   This produces:
 *     - At the center (distance=0): shade = 0.08 + 0.07 = 0.15
 *       (brightest, about 38/255 gray)
 *     - At the edge (distance=HUB_R): shade = 0.08 + 0.0 = 0.08
 *       (darkest, about 20/255 gray)
 *
 *   The result is a very dark, subtly convex-looking circle -- dark
 *   enough not to distract from the pointers, but with just enough
 *   gradient to read as a 3D surface rather than a flat dot.
 *
 *   The shade value (0.0 to 1.0) is converted to an 8-bit gray level
 *   and packed into all three color channels (R=G=B) to produce a
 *   neutral gray with no color cast.
 *
 * GEOMETRY:
 *   The hub is drawn as a filled circle of radius HUB_R=18 pixels,
 *   centered at (CX, CY). The circle test uses the standard
 *   dx^2 + dy^2 <= r^2 check (no sqrt needed).
 */
static void draw_hub(uint32_t *fb, int stride)
{
    for (int dy = -HUB_R; dy <= HUB_R; dy++)
        for (int dx = -HUB_R; dx <= HUB_R; dx++)
            if (dx*dx + dy*dy <= HUB_R*HUB_R) {
                int px = CX+dx, py = CY+dy;
                if ((unsigned)px < DISP_W && (unsigned)py < DISP_H) {
                    /* Radial gradient: brighter at center, darker at edge */
                    float shade = 0.08f + 0.07f * (1.0f - sqrtf(dx*dx+dy*dy)/(float)HUB_R);
                    uint8_t v = (uint8_t)(shade * 255);
                    /* Pack gray value into ARGB: 0xFF | v<<16 | v<<8 | v */
                    fb[py*stride+px] = 0xFF000000u | (v<<16) | (v<<8) | v;
                }
            }
}

/* ================================================================== */
/*  Main -- application entry point and event loop                    */
/* ================================================================== */
/*
 * The main function handles:
 *   1. UDP socket setup (Winsock) for transmitting to the Raspberry Pi
 *   2. Pre-rendering the static dial face (one-time cost)
 *   3. SDL2 window/renderer/texture creation
 *   4. The main event loop: input handling, animation, rendering,
 *      and UDP transmission at ~30 Hz
 *   5. Cleanup on exit
 *
 * ARCHITECTURE:
 *   The rendering pipeline each frame is:
 *     a) memcpy the pre-rendered dial face into the framebuffer
 *     b) Draw dynamic elements on top (Mach drum, flags, pointers, hub)
 *     c) Draw the control panel below the instrument
 *     d) Upload the framebuffer to an SDL texture and present it
 *
 *   The SDL renderer uses VSYNC (SDL_RENDERER_PRESENTVSYNC), so the
 *   frame rate is locked to the monitor refresh rate (typically 60 Hz).
 *   The UDP send rate is independent at ~30 Hz (every 33ms).
 *
 * ANIMATION:
 *   By default, the instrument runs an automatic animation that
 *   simulates a takeoff-to-cruise-and-back cycle over 30 seconds:
 *     - First 15 seconds: accelerate from 60 kts / M.10 to 390 kts / M.94
 *     - Next 15 seconds: decelerate back down
 *   This repeats indefinitely. Pressing SPACE toggles the animation
 *   off (manual control mode) or back on.
 *
 * CONTROL PANEL:
 *   Three groups of controls (IAS, MACH, VMO) with left/right arrow
 *   buttons. Clicking a button gives an initial discrete step; holding
 *   it down (after a 400ms delay) starts continuous adjustment
 *   proportional to frame time (dt), providing smooth analog control.
 */
int main(int argc, char *argv[])
{
    /* ---- UDP socket setup ---- */
    /* Default Pi IP address; can be overridden on the command line.
     * The Pi receiver listens on port 5555 for instrument packets. */
    const char *pi_ip = "192.168.1.129";
    if (argc > 1) pi_ip = argv[1];

    /* Initialize Winsock 2.2 and create a UDP datagram socket */
    WSADATA wsa; WSAStartup(MAKEWORD(2,2), &wsa);
    SOCKET sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    struct sockaddr_in pi_addr = {0};
    pi_addr.sin_family = AF_INET;
    pi_addr.sin_port = htons(PI_PORT);
    pi_addr.sin_addr.s_addr = inet_addr(pi_ip);
    printf("=== ASI Host → %s:%d ===\n", pi_ip, PI_PORT);

    /* ---- Pre-render the static dial face ---- */
    /*
     * Allocate a DISP_W x DISP_H buffer and render all static elements
     * (background, bezel, tick marks, numbers, labels) into it once.
     * This buffer will be memcpy'd into the active framebuffer each
     * frame, saving hundreds of trig/font computations per frame.
     */
    uint32_t *dial_bg = calloc(DISP_W * DISP_H, 4);
    render_dial_face(dial_bg, DISP_W);
    printf("Dial face rendered\n");

    /* The active framebuffer covers the full window (instrument + panel) */
    uint32_t *fb = calloc(WIN_W * WIN_H, 4);

    /* ---- SDL initialization ---- */
    /*
     * Create a window, hardware-accelerated renderer with VSYNC,
     * and a streaming texture for uploading our software-rendered
     * framebuffer to the GPU each frame. The texture format is
     * ARGB8888 to match our uint32_t pixel format.
     */
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *win = SDL_CreateWindow("ASI Host",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, WIN_W, WIN_H, 0);
    SDL_Renderer *ren = SDL_CreateRenderer(win, -1,
        SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    SDL_RenderSetLogicalSize(ren, WIN_W, WIN_H);
    SDL_Texture *tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888,
        SDL_TEXTUREACCESS_STREAMING, WIN_W, WIN_H);

    /* ---- Instrument state ---- */
    /*
     * ias       -- Current indicated airspeed in knots (60-500)
     * mach      -- Current Mach number for the drum display (0.10-0.99)
     * vmo       -- Current VMO setting for the barber-pole pointer (100-400)
     * auto_anim -- Whether the automatic animation is running
     * off_flag  -- Whether the OFF flag is displayed (not currently
     *              toggled in the UI, but the flag system is implemented)
     */
    float ias = 140, mach = 0.15f, vmo = 340;
    int auto_anim = 1, off_flag = 0;

    /* Button interaction state */
    int pressed_btn = -1;           /* index of currently pressed button (-1 = none) */
    Uint32 press_start = 0;         /* timestamp when button was first pressed */
    int initial_step_done = 0;      /* has the initial discrete step been applied? */
    Uint32 last_tick = SDL_GetTicks(), last_send = 0;

    /* Control panel group labels */
    static const char *labels[] = {"IAS", "MACH", "VMO"};

    /* ================================================================== */
    /*  Main event loop                                                   */
    /* ================================================================== */
    int running = 1;
    while (running) {
        /* ---- Frame timing ---- */
        /* Compute delta time (dt) for smooth animation regardless of
         * frame rate. Clamped to 100ms to prevent huge jumps if the
         * application is paused or the system hitches. */
        Uint32 now = SDL_GetTicks();
        float dt = (now-last_tick)/1000.0f;
        if (dt > 0.1f) dt = 0.1f;
        last_tick = now;

        /* Track mouse position for button hover highlighting */
        int mx, my;
        SDL_GetMouseState(&mx, &my);
        int hovered_btn = hit_test(mx, my);

        /* ---- Event handling ---- */
        SDL_Event ev;
        while (SDL_PollEvent(&ev)) {
            switch (ev.type) {
            case SDL_QUIT: running=0; break;
            case SDL_KEYDOWN:
                switch(ev.key.keysym.sym) {
                case SDLK_ESCAPE: running=0; break;
                case SDLK_SPACE: auto_anim=!auto_anim; break;
                case SDLK_r: ias=140; mach=0.15f; vmo=340; auto_anim=1; break;
                default: break;
                } break;
            case SDL_MOUSEBUTTONDOWN:
                if(ev.button.button==SDL_BUTTON_LEFT){
                    pressed_btn=hit_test(ev.button.x,ev.button.y);
                    press_start=now; initial_step_done=0;
                } break;
            case SDL_MOUSEBUTTONUP:
                if(ev.button.button==SDL_BUTTON_LEFT) pressed_btn=-1; break;
            }
        }

        /* ---- Button actions (click and hold) ---- */
        /*
         * Button behavior:
         *   - On first press: apply a discrete step (e.g., +5 kts for IAS)
         *   - After holding for 400ms: switch to continuous adjustment
         *     proportional to dt, giving smooth analog control
         *   - Pressing an IAS or MACH button disables auto_anim
         *   - VMO buttons do NOT disable auto_anim (VMO is independent)
         */
        if (pressed_btn >= 0) {
            int dir=(pressed_btn&1)?1:-1, group=pressed_btn/2;
            float *target=NULL, step=0, cont=0;
            switch(group){
            case 0: target=&ias;  step=5; cont=60*dt; auto_anim=0; break;
            case 1: target=&mach; step=0.01f; cont=0.05f*dt; auto_anim=0; break;
            case 2: target=&vmo;  step=5; cont=60*dt; break;
            }
            if(target){
                /* First click: discrete step. Hold: continuous after 400ms delay. */
                if(!initial_step_done){*target+=dir*step;initial_step_done=1;}
                else if(now-press_start>400)*target+=dir*cont;
            }
        }

        /* ---- Keyboard continuous controls ---- */
        /* Arrow keys and Q/W provide continuous adjustment while held.
         * Rate: 60 kts/sec for IAS/VMO, 0.05 Mach/sec for Mach. */
        const Uint8 *keys = SDL_GetKeyboardState(NULL);
        if(keys[SDL_SCANCODE_UP])    { ias+=60*dt; auto_anim=0; }
        if(keys[SDL_SCANCODE_DOWN])  { ias-=60*dt; auto_anim=0; }
        if(keys[SDL_SCANCODE_LEFT])  vmo-=60*dt;
        if(keys[SDL_SCANCODE_RIGHT]) vmo+=60*dt;
        if(keys[SDL_SCANCODE_Q])     { mach-=0.05f*dt; auto_anim=0; }
        if(keys[SDL_SCANCODE_W])     { mach+=0.05f*dt; auto_anim=0; }

        /* ---- Auto animation: takeoff to cruise and back ---- */
        /*
         * A repeating 30-second cycle that sweeps through the full
         * operating range of the instrument:
         *
         *   t = 0..15 seconds:  Acceleration phase
         *     IAS:  60 → 390 kts  (60 + t*22)
         *     Mach: .10 → .94     (.10 + t*0.056)
         *
         *   t = 15..30 seconds: Deceleration phase (mirror of above)
         *     IAS:  390 → 60 kts
         *     Mach: .94 → .10
         *
         * This exercises the full sweep of the IAS pointer across the
         * non-linear scale, demonstrating the compressed high-speed
         * region and the expanded low-speed region.
         */
        if (auto_anim) {
            float t = fmodf(now / 1000.0f, 30.0f);
            if (t < 15) {
                ias = 60 + t * 22;       /* 60→390 over 15s */
                mach = 0.10f + t * 0.056f;  /* .10→.94 */
            } else {
                ias = 390 - (t-15) * 22;
                mach = 0.94f - (t-15) * 0.056f;
            }
        }

        /* ---- Clamp all values to valid ranges ---- */
        if(ias<60) ias=60; if(ias>500) ias=500;
        if(mach<0.10f) mach=0.10f; if(mach>0.99f) mach=0.99f;
        if(vmo<100) vmo=100; if(vmo>400) vmo=400;

        /* ---- VMO overspeed warning ---- */
        /* If the current IAS exceeds VMO, the VMO flag is displayed.
         * On a real aircraft this would also trigger aural warnings. */
        int vmo_warn = (ias > vmo);

        /* ---- Send UDP packet to Raspberry Pi ---- */
        /*
         * Transmit the current instrument state at ~30 Hz (every 33ms).
         * The packet is a simple 16-byte AsiPacket struct containing
         * the instrument ID, IAS, Mach, and VMO values. The Pi
         * receiver uses the instrument_id field to route the packet
         * to the correct rendering pipeline.
         *
         * No acknowledgment or flow control -- pure fire-and-forget
         * UDP. If a packet is lost, the next one arrives 33ms later
         * with updated values. This is appropriate for real-time
         * instrument data where the latest value is always the most
         * relevant.
         */
        if (now-last_send >= SEND_INTERVAL) {
            AsiPacket pkt = {INSTRUMENT_ASI, ias, mach, vmo};
            sendto(sock,(char*)&pkt,sizeof(pkt),0,
                   (struct sockaddr*)&pi_addr,sizeof(pi_addr));
            last_send = now;
        }

        /* ================================================================ */
        /*  Render the complete frame                                       */
        /* ================================================================ */

        /* Step 1: Copy the pre-rendered static dial face into the
         * instrument area of the framebuffer. This is a fast memcpy
         * of 480*480*4 = 921,600 bytes -- far cheaper than re-rendering
         * all the tick marks, numbers, and legends from scratch. */
        for (int y = 0; y < DISP_H; y++)
            memcpy(&fb[y*WIN_W], &dial_bg[y*DISP_W], DISP_W*4);

        /* Step 2: Draw dynamic elements on top of the static face.
         * Draw order matters -- later elements overlap earlier ones:
         *   - Mach drum (behind pointers)
         *   - Flag (behind pointers)
         *   - VMO barber-pole pointer (behind IAS pointer)
         *   - IAS pointer (primary indication, on top)
         *   - Center hub (covers pointer bases) */
        draw_mach_display(fb, WIN_W, mach);
        draw_flag(fb, WIN_W, off_flag, vmo_warn);
        draw_vmo_pointer(fb, WIN_W, kts_to_deg(vmo));
        draw_ias_pointer(fb, WIN_W, kts_to_deg(ias));
        draw_hub(fb, WIN_W);

        /* Step 3: Draw the control panel below the instrument face.
         * The panel has a dark background, thin separator lines between
         * groups, and for each of the 3 groups: a label, a numeric
         * readout, and two arrow buttons. */
        fill_rect(fb, 0, DISP_H, WIN_W, PANEL_H, COL_PANEL_BG);
        fill_rect(fb, 0, DISP_H, WIN_W, 1, COL_SEPARATOR);   /* top border */
        for (int g=1; g<N_CONTROLS; g++)
            fill_rect(fb, g*GROUP_W, DISP_H+4, 1, PANEL_H-8, COL_SEPARATOR);

        for (int g=0; g<N_CONTROLS; g++) {
            int gcx = g*GROUP_W + GROUP_W/2;   /* horizontal center of group */
            draw_str_cx_flat(fb, gcx, LABEL_Y, labels[g], COL_LABEL);
            /* Format the current value for display */
            char val[16];
            switch(g){
            case 0: snprintf(val,sizeof(val),"%03.0f",ias); break;     /* "140" */
            case 1: snprintf(val,sizeof(val),".%02d",(int)(mach*100+0.5f)); break; /* ".84" */
            case 2: snprintf(val,sizeof(val),"%03.0f",vmo); break;     /* "340" */
            }
            draw_str_cx_flat(fb, gcx, VALUE_Y, val, COL_VALUE_G);
            /* Left and right arrow buttons with hover/press state */
            draw_button(fb,BTN_L_X(g),BTN_Y,-1,hovered_btn==g*2,pressed_btn==g*2);
            draw_button(fb,BTN_R_X(g),BTN_Y, 1,hovered_btn==g*2+1,pressed_btn==g*2+1);
        }

        /* Step 4: Upload the completed framebuffer to the GPU texture
         * and present it. SDL_RenderPresent blocks until the next
         * VSYNC if SDL_RENDERER_PRESENTVSYNC is enabled. */
        SDL_UpdateTexture(tex,NULL,fb,WIN_W*4);
        SDL_RenderCopy(ren,tex,NULL,NULL);
        SDL_RenderPresent(ren);
    }

    /* ---- Cleanup ---- */
    closesocket(sock); WSACleanup();
    free(dial_bg); free(fb);
    SDL_DestroyTexture(tex); SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win); SDL_Quit();
    return 0;
}
